//! Phase 152 C02f-BL private production attempt-ID generation for acquisition preparation.
//!
//! C02f-BH selected control-plane ownership, the existing `aws-lc-rs` `SystemRandom` provider,
//! independent 32-byte fills for the sequence-allocation and live-owner authority domains, and
//! fail-closed handling without retry or fallback. This module materializes only that generation
//! boundary. It performs no provider persistence I/O, mutation planning, endpoint/client setup,
//! runtime activation, deployment, or semantic grant mapping.

use std::fmt;

use aws_lc_rs::rand::{SecureRandom, SystemRandom};

use crate::{
    fence_sequence::SequenceAllocationAttemptId, reachability_live_owner_codec::AuthorityAttemptId,
};

const ATTEMPT_ID_BYTES: usize = 32;

/// Bounded fail-closed attempt-ID generation failure for acquisition preparation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReachabilityAttemptIdGenerationError {
    /// The selected cryptographic provider could not fill the requested destination.
    RandomnessUnavailable,
    /// Generated sequence-allocation bytes were rejected by the existing typed constructor.
    SequenceAllocationRejected,
    /// Generated live-owner authority bytes were rejected by the existing typed constructor.
    AuthorityRejected,
}

impl fmt::Display for ReachabilityAttemptIdGenerationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let message = match self {
            Self::RandomnessUnavailable => "attempt-ID cryptographic randomness unavailable",
            Self::SequenceAllocationRejected => "generated sequence-allocation attempt ID rejected",
            Self::AuthorityRejected => "generated live-owner authority attempt ID rejected",
        };
        formatter.write_str(message)
    }
}

impl std::error::Error for ReachabilityAttemptIdGenerationError {}

/// Generates one fresh sequence-allocation attempt identifier for one new logical allocation.
///
/// Exactly one provider fill is attempted. Provider failure or typed all-zero rejection fails
/// closed; this helper performs no retry, fallback, mutation planning, or persistence operation.
///
/// # Errors
///
/// Returns a bounded generation error when cryptographic randomness is unavailable or when the
/// existing sequence-allocation typed constructor rejects the generated bytes.
pub fn generate_sequence_allocation_attempt_id()
-> Result<SequenceAllocationAttemptId, ReachabilityAttemptIdGenerationError> {
    generate_sequence_allocation_attempt_id_with(fill_system_random)
}

/// Generates one fresh live-owner authority attempt identifier for one new logical mutation.
///
/// Exactly one independent provider fill is attempted. Provider failure or typed all-zero rejection
/// fails closed; this helper performs no retry, fallback, mutation planning, or persistence operation.
///
/// # Errors
///
/// Returns a bounded generation error when cryptographic randomness is unavailable or when the
/// existing live-owner authority typed constructor rejects the generated bytes.
pub fn generate_authority_attempt_id()
-> Result<AuthorityAttemptId, ReachabilityAttemptIdGenerationError> {
    generate_authority_attempt_id_with(fill_system_random)
}

fn fill_system_random(
    destination: &mut [u8; ATTEMPT_ID_BYTES],
) -> Result<(), ReachabilityAttemptIdGenerationError> {
    SystemRandom::new()
        .fill(destination)
        .map_err(|_| ReachabilityAttemptIdGenerationError::RandomnessUnavailable)
}

fn generate_sequence_allocation_attempt_id_with(
    fill: impl FnOnce(&mut [u8; ATTEMPT_ID_BYTES]) -> Result<(), ReachabilityAttemptIdGenerationError>,
) -> Result<SequenceAllocationAttemptId, ReachabilityAttemptIdGenerationError> {
    let mut bytes = [0_u8; ATTEMPT_ID_BYTES];
    fill(&mut bytes)?;
    SequenceAllocationAttemptId::new(bytes)
        .map_err(|_| ReachabilityAttemptIdGenerationError::SequenceAllocationRejected)
}

fn generate_authority_attempt_id_with(
    fill: impl FnOnce(&mut [u8; ATTEMPT_ID_BYTES]) -> Result<(), ReachabilityAttemptIdGenerationError>,
) -> Result<AuthorityAttemptId, ReachabilityAttemptIdGenerationError> {
    let mut bytes = [0_u8; ATTEMPT_ID_BYTES];
    fill(&mut bytes)?;
    AuthorityAttemptId::new(bytes)
        .map_err(|_| ReachabilityAttemptIdGenerationError::AuthorityRejected)
}

#[cfg(test)]
mod tests {
    use std::cell::Cell;

    use super::*;

    #[test]
    fn sequence_generation_uses_one_fill_and_exact_typed_bytes() {
        let calls = Cell::new(0_u8);
        let expected = [0x31_u8; ATTEMPT_ID_BYTES];

        let generated = generate_sequence_allocation_attempt_id_with(|destination| {
            calls.set(calls.get() + 1);
            destination.copy_from_slice(&expected);
            Ok(())
        })
        .expect("non-zero sequence attempt ID");

        assert_eq!(calls.get(), 1);
        assert_eq!(generated.as_bytes(), &expected);
    }

    #[test]
    fn authority_generation_uses_one_independent_fill_and_exact_typed_bytes() {
        let calls = Cell::new(0_u8);
        let expected = [0x72_u8; ATTEMPT_ID_BYTES];

        let generated = generate_authority_attempt_id_with(|destination| {
            calls.set(calls.get() + 1);
            destination.copy_from_slice(&expected);
            Ok(())
        })
        .expect("non-zero authority attempt ID");

        assert_eq!(calls.get(), 1);
        assert_eq!(generated.as_bytes(), &expected);
    }

    #[test]
    fn provider_failure_is_not_retried_for_sequence_generation() {
        let calls = Cell::new(0_u8);

        let result = generate_sequence_allocation_attempt_id_with(|_destination| {
            calls.set(calls.get() + 1);
            Err(ReachabilityAttemptIdGenerationError::RandomnessUnavailable)
        });

        assert_eq!(calls.get(), 1);
        assert_eq!(
            result,
            Err(ReachabilityAttemptIdGenerationError::RandomnessUnavailable)
        );
    }

    #[test]
    fn provider_failure_is_not_retried_for_authority_generation() {
        let calls = Cell::new(0_u8);

        let result = generate_authority_attempt_id_with(|_destination| {
            calls.set(calls.get() + 1);
            Err(ReachabilityAttemptIdGenerationError::RandomnessUnavailable)
        });

        assert_eq!(calls.get(), 1);
        assert_eq!(
            result,
            Err(ReachabilityAttemptIdGenerationError::RandomnessUnavailable)
        );
    }

    #[test]
    fn all_zero_sequence_bytes_fail_closed_without_retry() {
        let calls = Cell::new(0_u8);

        let result = generate_sequence_allocation_attempt_id_with(|_destination| {
            calls.set(calls.get() + 1);
            Ok(())
        });

        assert_eq!(calls.get(), 1);
        assert_eq!(
            result,
            Err(ReachabilityAttemptIdGenerationError::SequenceAllocationRejected)
        );
    }

    #[test]
    fn all_zero_authority_bytes_fail_closed_without_retry() {
        let calls = Cell::new(0_u8);

        let result = generate_authority_attempt_id_with(|_destination| {
            calls.set(calls.get() + 1);
            Ok(())
        });

        assert_eq!(calls.get(), 1);
        assert_eq!(
            result,
            Err(ReachabilityAttemptIdGenerationError::AuthorityRejected)
        );
    }
}
