use std::{
    fs::File,
    io,
    os::{fd::OwnedFd, unix::fs::FileExt},
};

use aws_lc_rs::digest::{Context, SHA256};
use rustix::{
    fs::{
        AtFlags, Mode, OFlags, RenameFlags, fchmod, fstat, openat, renameat_with, unlinkat,
    },
    io::{Errno, dup},
    process::geteuid,
};

use super::{AnchoredFileRoot, FileServiceError, RemoteFileType, RemotePath, classify_mode};

const STAGING_PREFIX: &str = ".prw-upload-";
const STAGING_SUFFIX: &str = ".part";
const STAGING_HEX_LEN: usize = 32;
const STAGING_NAME_LEN: usize = STAGING_PREFIX.len() + STAGING_HEX_LEN + STAGING_SUFFIX.len();
const TRANSFER_FILE_MODE: Mode = Mode::from_bits_retain(0o600);
const OPEN_NEW_STAGING: OFlags = OFlags::RDWR
    .union(OFlags::CREATE)
    .union(OFlags::EXCL)
    .union(OFlags::NOFOLLOW)
    .union(OFlags::CLOEXEC);
const OPEN_EXISTING_STAGING: OFlags = OFlags::RDWR.union(OFlags::NOFOLLOW).union(OFlags::CLOEXEC);
const OPEN_DOWNLOAD: OFlags = OFlags::RDONLY.union(OFlags::NOFOLLOW).union(OFlags::CLOEXEC);

/// Maximum one-shot storage chunk accepted by the Phase 132 primitive.
pub const MAX_TRANSFER_CHUNK_BYTES: usize = 1_048_576;

/// Descriptor-anchored staging-file failure classification.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum TransferStorageError {
    /// Generated staging name did not match the reserved exact shape.
    InvalidStagingName,
    /// Staging destination already exists.
    StagingAlreadyExists,
    /// Staging destination does not exist for resume/abort.
    StagingMissing,
    /// Staging object is not the exact regular same-user 0600 object required.
    UnsafeStagingObject,
    /// Supplied write offset differs from the exact current staged length.
    OffsetMismatch,
    /// Chunk was empty or exceeded the one-chunk byte bound.
    InvalidChunkLength,
    /// Final destination already exists; overwrite is forbidden.
    FinalDestinationExists,
    /// Bounded filesystem operation failed.
    Filesystem,
}

impl std::fmt::Display for TransferStorageError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let message = match self {
            Self::InvalidStagingName => "invalid PRW staging name",
            Self::StagingAlreadyExists => "PRW staging file already exists",
            Self::StagingMissing => "PRW staging file is missing",
            Self::UnsafeStagingObject => "unsafe PRW staging object",
            Self::OffsetMismatch => "PRW staging offset mismatch",
            Self::InvalidChunkLength => "invalid PRW transfer chunk length",
            Self::FinalDestinationExists => "final destination already exists",
            Self::Filesystem => "PRW transfer storage operation failed",
        };
        formatter.write_str(message)
    }
}

impl std::error::Error for TransferStorageError {}

/// Same-directory descriptor-anchored staging handle.
#[derive(Debug)]
pub struct StagedUploadFile {
    parent: OwnedFd,
    file: OwnedFd,
    staging_name: String,
    final_name: String,
}

impl AnchoredFileRoot {
    /// Begins one creation-only same-directory staging file.
    ///
    /// `staging_name` must be generated by [`crate::transfer_staging_name`] or match
    /// its exact reserved shape.
    ///
    /// # Errors
    ///
    /// Rejects root destinations, invalid generated names, existing staging objects,
    /// path-resolution failures, or unsafe post-create metadata.
    pub fn begin_staged_upload(
        &self,
        destination: &RemotePath,
        staging_name: &str,
    ) -> Result<StagedUploadFile, TransferStorageError> {
        validate_staging_name(staging_name)?;
        let (parent, final_name) = self
            .open_parent(destination)
            .map_err(map_file_service_error)?;
        let file = openat(&parent, staging_name, OPEN_NEW_STAGING, TRANSFER_FILE_MODE)
            .map_err(map_begin_error)?;
        fchmod(&file, TRANSFER_FILE_MODE).map_err(|_| TransferStorageError::Filesystem)?;
        validate_staging_fd(&file)?;
        Ok(StagedUploadFile {
            parent,
            file,
            staging_name: staging_name.to_owned(),
            final_name: final_name.to_owned(),
        })
    }

    /// Resumes one exact existing same-directory staging file.
    ///
    /// # Errors
    ///
    /// Rejects root destinations, invalid generated names, missing/unsafe staging
    /// objects, or descriptor-relative resolution failure.
    pub fn resume_staged_upload(
        &self,
        destination: &RemotePath,
        staging_name: &str,
    ) -> Result<StagedUploadFile, TransferStorageError> {
        validate_staging_name(staging_name)?;
        let (parent, final_name) = self
            .open_parent(destination)
            .map_err(map_file_service_error)?;
        let file = openat(&parent, staging_name, OPEN_EXISTING_STAGING, Mode::empty())
            .map_err(map_resume_error)?;
        validate_staging_fd(&file)?;
        Ok(StagedUploadFile {
            parent,
            file,
            staging_name: staging_name.to_owned(),
            final_name: final_name.to_owned(),
        })
    }

    /// Reads one bounded chunk from a regular file without following the final symlink.
    ///
    /// # Errors
    ///
    /// Rejects root paths, zero/oversize chunk lengths, non-regular files, path
    /// resolution failure, or bounded read failure.
    pub fn read_download_chunk(
        &self,
        path: &RemotePath,
        offset: u64,
        requested_len: usize,
    ) -> Result<Vec<u8>, TransferStorageError> {
        if requested_len == 0 || requested_len > MAX_TRANSFER_CHUNK_BYTES {
            return Err(TransferStorageError::InvalidChunkLength);
        }
        let (parent, final_name) = self.open_parent(path).map_err(map_file_service_error)?;
        let fd = openat(&parent, final_name, OPEN_DOWNLOAD, Mode::empty())
            .map_err(|_| TransferStorageError::Filesystem)?;
        let stat = fstat(&fd).map_err(|_| TransferStorageError::Filesystem)?;
        if classify_mode(stat.st_mode) != RemoteFileType::RegularFile {
            return Err(TransferStorageError::Filesystem);
        }
        let file = File::from(fd);
        let mut buffer = vec![0_u8; requested_len];
        let read = file
            .read_at(&mut buffer, offset)
            .map_err(|_| TransferStorageError::Filesystem)?;
        buffer.truncate(read);
        Ok(buffer)
    }
}

impl StagedUploadFile {
    /// Returns the exact current staged byte length.
    ///
    /// # Errors
    ///
    /// Rejects unsafe metadata or filesystem failure.
    pub fn len(&self) -> Result<u64, TransferStorageError> {
        validate_staging_fd(&self.file)?;
        let stat = fstat(&self.file).map_err(|_| TransferStorageError::Filesystem)?;
        u64::try_from(stat.st_size).map_err(|_| TransferStorageError::UnsafeStagingObject)
    }

    /// Returns whether the staging file currently contains zero bytes.
    ///
    /// # Errors
    ///
    /// Propagates [`Self::len`] validation failure.
    pub fn is_empty(&self) -> Result<bool, TransferStorageError> {
        Ok(self.len()? == 0)
    }

    /// Writes and syncs one chunk at the exact current end offset.
    ///
    /// # Errors
    ///
    /// Rejects empty/oversize chunks, offset mismatch, unsafe metadata, short/failed
    /// writes, or sync failure.
    pub fn write_chunk(&self, offset: u64, chunk: &[u8]) -> Result<u64, TransferStorageError> {
        if chunk.is_empty() || chunk.len() > MAX_TRANSFER_CHUNK_BYTES {
            return Err(TransferStorageError::InvalidChunkLength);
        }
        let current = self.len()?;
        if offset != current {
            return Err(TransferStorageError::OffsetMismatch);
        }
        let file = File::from(dup(&self.file).map_err(|_| TransferStorageError::Filesystem)?);
        write_all_at(&file, chunk, offset)?;
        file.sync_all()
            .map_err(|_| TransferStorageError::Filesystem)?;
        let new_len = self.len()?;
        if new_len != current.saturating_add(chunk.len() as u64) {
            return Err(TransferStorageError::Filesystem);
        }
        Ok(new_len)
    }

    /// Computes SHA-256 over the exact staged bytes using bounded streaming reads.
    ///
    /// # Errors
    ///
    /// Rejects unsafe staging metadata or read failure.
    pub fn sha256(&self) -> Result<[u8; 32], TransferStorageError> {
        validate_staging_fd(&self.file)?;
        let file = File::from(dup(&self.file).map_err(|_| TransferStorageError::Filesystem)?);
        let total = self.len()?;
        let mut context = Context::new(&SHA256);
        let mut offset = 0_u64;
        let mut buffer = vec![0_u8; 64 * 1024];
        while offset < total {
            let remaining = total - offset;
            let wanted = usize::try_from(remaining.min(buffer.len() as u64))
                .map_err(|_| TransferStorageError::Filesystem)?;
            let read = file
                .read_at(&mut buffer[..wanted], offset)
                .map_err(|_| TransferStorageError::Filesystem)?;
            if read == 0 {
                return Err(TransferStorageError::Filesystem);
            }
            context.update(&buffer[..read]);
            offset = offset
                .checked_add(read as u64)
                .ok_or(TransferStorageError::Filesystem)?;
        }
        let digest = context.finish();
        let mut value = [0_u8; 32];
        value.copy_from_slice(digest.as_ref());
        Ok(value)
    }

    /// Atomically publishes the staging file only when the final destination is absent.
    ///
    /// # Errors
    ///
    /// Rejects unsafe staging metadata, preexisting final destination, rename failure,
    /// or parent-directory sync failure.
    pub fn commit_noreplace(self) -> Result<(), TransferStorageError> {
        validate_staging_fd(&self.file)?;
        File::from(dup(&self.file).map_err(|_| TransferStorageError::Filesystem)?)
            .sync_all()
            .map_err(|_| TransferStorageError::Filesystem)?;
        renameat_with(
            &self.parent,
            self.staging_name.as_str(),
            &self.parent,
            self.final_name.as_str(),
            RenameFlags::NOREPLACE,
        )
        .map_err(map_commit_error)?;
        File::from(dup(&self.parent).map_err(|_| TransferStorageError::Filesystem)?)
            .sync_all()
            .map_err(|_| TransferStorageError::Filesystem)
    }

    /// Removes only the exact staging entry, never the final destination.
    ///
    /// # Errors
    ///
    /// Rejects unsafe staging identity or bounded unlink/sync failure.
    pub fn abort(self) -> Result<(), TransferStorageError> {
        validate_staging_fd(&self.file)?;
        let path_stat = rustix::fs::statat(
            &self.parent,
            self.staging_name.as_str(),
            AtFlags::SYMLINK_NOFOLLOW,
        )
        .map_err(map_resume_error)?;
        let fd_stat = fstat(&self.file).map_err(|_| TransferStorageError::Filesystem)?;
        if path_stat.st_dev != fd_stat.st_dev || path_stat.st_ino != fd_stat.st_ino {
            return Err(TransferStorageError::UnsafeStagingObject);
        }
        unlinkat(&self.parent, self.staging_name.as_str(), AtFlags::empty())
            .map_err(|_| TransferStorageError::Filesystem)?;
        File::from(dup(&self.parent).map_err(|_| TransferStorageError::Filesystem)?)
            .sync_all()
            .map_err(|_| TransferStorageError::Filesystem)
    }
}

/// Generates the exact reserved staging filename from 16 transfer-id bytes.
#[must_use]
pub fn transfer_staging_name(id: [u8; 16]) -> String {
    let mut output = String::with_capacity(STAGING_NAME_LEN);
    output.push_str(STAGING_PREFIX);
    for byte in id {
        use std::fmt::Write as _;
        write!(&mut output, "{byte:02x}").expect("write to String");
    }
    output.push_str(STAGING_SUFFIX);
    output
}

fn validate_staging_name(name: &str) -> Result<(), TransferStorageError> {
    if name.len() != STAGING_NAME_LEN
        || !name.starts_with(STAGING_PREFIX)
        || !name.ends_with(STAGING_SUFFIX)
    {
        return Err(TransferStorageError::InvalidStagingName);
    }
    let hex = &name[STAGING_PREFIX.len()..STAGING_PREFIX.len() + STAGING_HEX_LEN];
    if !hex.bytes().all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase()) {
        return Err(TransferStorageError::InvalidStagingName);
    }
    Ok(())
}

fn validate_staging_fd(fd: &OwnedFd) -> Result<(), TransferStorageError> {
    let stat = fstat(fd).map_err(|_| TransferStorageError::Filesystem)?;
    if classify_mode(stat.st_mode) != RemoteFileType::RegularFile
        || stat.st_mode & 0o777 != 0o600
        || stat.st_uid != geteuid().as_raw()
    {
        return Err(TransferStorageError::UnsafeStagingObject);
    }
    Ok(())
}

fn write_all_at(file: &File, mut bytes: &[u8], mut offset: u64) -> Result<(), TransferStorageError> {
    while !bytes.is_empty() {
        match file.write_at(bytes, offset) {
            Ok(0) => return Err(TransferStorageError::Filesystem),
            Ok(written) => {
                bytes = &bytes[written..];
                offset = offset
                    .checked_add(written as u64)
                    .ok_or(TransferStorageError::Filesystem)?;
            }
            Err(error) if error.kind() == io::ErrorKind::Interrupted => {}
            Err(_) => return Err(TransferStorageError::Filesystem),
        }
    }
    Ok(())
}

const fn map_file_service_error(error: FileServiceError) -> TransferStorageError {
    match error {
        FileServiceError::AlreadyExists => TransferStorageError::FinalDestinationExists,
        _ => TransferStorageError::Filesystem,
    }
}

fn map_begin_error(error: Errno) -> TransferStorageError {
    if error == Errno::EXIST {
        TransferStorageError::StagingAlreadyExists
    } else {
        TransferStorageError::Filesystem
    }
}

fn map_resume_error(error: Errno) -> TransferStorageError {
    if error == Errno::NOENT {
        TransferStorageError::StagingMissing
    } else {
        TransferStorageError::Filesystem
    }
}

fn map_commit_error(error: Errno) -> TransferStorageError {
    if error == Errno::EXIST {
        TransferStorageError::FinalDestinationExists
    } else {
        TransferStorageError::Filesystem
    }
}
