//! Canonical Phase 152 C02f-Z live-owner key/value codec for the etcd authority boundary.
//!
//! This module is deliberately pure and runtime-independent. It performs no etcd request,
//! network I/O, retry, TLS setup, task spawn, fence allocation, randomness generation or
//! production activation. It only materializes the selected exact-peer key and `PRWL` v1.0
//! authority-record encodings plus fail-closed validation.

use std::{fmt, num::NonZeroU128, str};

use prw_connectivity::{PeerConnectivityIdentity, TransportIdentity};
use prw_core::DeviceId;

/// Exact fixed binary-key domain prefix selected by C02f-Z.
pub const LIVE_OWNER_KEY_PREFIX: &[u8] = b"/prw/reachability/live-owner/";
/// Initial live-owner key major version.
pub const LIVE_OWNER_KEY_MAJOR: u16 = 1;
/// Initial live-owner key minor version.
pub const LIVE_OWNER_KEY_MINOR: u16 = 0;
/// Exact authority-record magic selected by C02f-Z.
pub const LIVE_OWNER_RECORD_MAGIC: [u8; 4] = *b"PRWL";
/// Initial authority-record major version.
pub const LIVE_OWNER_RECORD_MAJOR: u16 = 1;
/// Initial authority-record minor version.
pub const LIVE_OWNER_RECORD_MINOR: u16 = 0;
/// Fixed authority-record header bytes before the DeviceId length field.
pub const LIVE_OWNER_RECORD_HEADER_BYTES: usize = 12;
/// Fixed encoded PRW fence width.
pub const LIVE_OWNER_FENCE_BYTES: usize = 16;
/// Fixed internal authority-attempt identifier width.
pub const AUTHORITY_ATTEMPT_ID_BYTES: usize = 32;
/// Fixed authority-record bytes excluding the variable DeviceId UTF-8 payload.
pub const LIVE_OWNER_RECORD_FIXED_BYTES: usize = 100;

const TRANSPORT_IDENTITY_BYTES: usize = 32;
const DEVICE_ID_LENGTH_BYTES: usize = 8;
const KEY_VERSION_BYTES: usize = 4;

/// Canonical persisted live-owner lifecycle discriminator.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum LiveOwnerLifecycle {
    /// The exact peer currently owns the persisted authority generation.
    Current = 1,
    /// The exact peer generation has been released while retaining its high-water fence.
    Released = 2,
}

impl LiveOwnerLifecycle {
    const fn encoded(self) -> u16 {
        self as u16
    }
}

impl TryFrom<u16> for LiveOwnerLifecycle {
    type Error = ReachabilityLiveOwnerCodecError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            1 => Ok(Self::Current),
            2 => Ok(Self::Released),
            _ => Err(ReachabilityLiveOwnerCodecError::InvalidLifecycle),
        }
    }
}

/// Non-zero provider-internal identifier for one logical authority mutation attempt.
///
/// C02f-Z requires cryptographically strong process-local generation later. This type only
/// validates and carries already-generated bytes; it intentionally does not select an RNG API.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct AuthorityAttemptId([u8; AUTHORITY_ATTEMPT_ID_BYTES]);

impl AuthorityAttemptId {
    /// Creates one non-zero authority-attempt identifier.
    ///
    /// # Errors
    ///
    /// Returns [`ReachabilityLiveOwnerCodecError::ZeroAuthorityAttemptId`] for all-zero bytes.
    pub fn new(
        bytes: [u8; AUTHORITY_ATTEMPT_ID_BYTES],
    ) -> Result<Self, ReachabilityLiveOwnerCodecError> {
        if bytes.iter().all(|byte| *byte == 0) {
            return Err(ReachabilityLiveOwnerCodecError::ZeroAuthorityAttemptId);
        }
        Ok(Self(bytes))
    }

    /// Returns the exact opaque attempt bytes.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; AUTHORITY_ATTEMPT_ID_BYTES] {
        &self.0
    }
}

/// One canonical decoded `PRWL` v1.0 authority record.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReachabilityLiveOwnerAuthorityRecord {
    peer: PeerConnectivityIdentity,
    lifecycle: LiveOwnerLifecycle,
    fence: NonZeroU128,
    attempt_id: AuthorityAttemptId,
}

impl ReachabilityLiveOwnerAuthorityRecord {
    /// Creates a canonical Current record from already-validated typed fields.
    #[must_use]
    pub const fn current(
        peer: PeerConnectivityIdentity,
        fence: NonZeroU128,
        attempt_id: AuthorityAttemptId,
    ) -> Self {
        Self {
            peer,
            lifecycle: LiveOwnerLifecycle::Current,
            fence,
            attempt_id,
        }
    }

    /// Returns a Released successor preserving the exact peer, fence and attempt identifier.
    ///
    /// This is a pure record transformation only; it performs no persistence mutation.
    #[must_use]
    pub fn released_successor(&self) -> Self {
        Self {
            peer: self.peer.clone(),
            lifecycle: LiveOwnerLifecycle::Released,
            fence: self.fence,
            attempt_id: self.attempt_id,
        }
    }

    /// Returns the exact peer identity bound inside the record.
    #[must_use]
    pub const fn peer(&self) -> &PeerConnectivityIdentity {
        &self.peer
    }

    /// Returns the persisted lifecycle discriminator.
    #[must_use]
    pub const fn lifecycle(&self) -> LiveOwnerLifecycle {
        self.lifecycle
    }

    /// Returns the full non-zero application-owned fence value.
    #[must_use]
    pub const fn fence(&self) -> NonZeroU128 {
        self.fence
    }

    /// Returns the provider-internal attempt identifier.
    #[must_use]
    pub const fn attempt_id(&self) -> AuthorityAttemptId {
        self.attempt_id
    }
}

/// Fail-closed canonical codec/identity-binding validation failure.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReachabilityLiveOwnerCodecError {
    /// Key does not start with the selected exact live-owner domain prefix.
    InvalidKeyPrefix,
    /// Key major/minor version is not the selected v1.0 pair.
    UnsupportedKeyVersion,
    /// Key length field or total encoded length is invalid/non-canonical.
    InvalidKeyLength,
    /// DeviceId bytes are invalid UTF-8 or violate the existing DeviceId constructor.
    InvalidDeviceId,
    /// TransportIdentity bytes are invalid, including the prohibited all-zero value.
    InvalidTransportIdentity,
    /// Authority record does not start with exact `PRWL` magic.
    InvalidRecordMagic,
    /// Authority record major/minor version is not the selected v1.0 pair.
    UnsupportedRecordVersion,
    /// Authority record lifecycle discriminator is unknown.
    InvalidLifecycle,
    /// Authority record reserved flags are not exactly zero.
    NonZeroReservedFlags,
    /// Authority record length field or total encoded length is invalid/non-canonical.
    InvalidRecordLength,
    /// Persisted PRW fence is zero.
    ZeroFence,
    /// Authority-attempt identifier is all zero.
    ZeroAuthorityAttemptId,
    /// Decoded record peer does not exactly match the peer encoded by its etcd key.
    PeerBindingMismatch,
    /// Host-size/capacity conversion overflow prevented canonical encoding.
    LengthOverflow,
}

impl fmt::Display for ReachabilityLiveOwnerCodecError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let message = match self {
            Self::InvalidKeyPrefix => "invalid live-owner key prefix",
            Self::UnsupportedKeyVersion => "unsupported live-owner key version",
            Self::InvalidKeyLength => "invalid live-owner key length",
            Self::InvalidDeviceId => "invalid live-owner DeviceId bytes",
            Self::InvalidTransportIdentity => "invalid live-owner TransportIdentity bytes",
            Self::InvalidRecordMagic => "invalid live-owner record magic",
            Self::UnsupportedRecordVersion => "unsupported live-owner record version",
            Self::InvalidLifecycle => "invalid live-owner record lifecycle",
            Self::NonZeroReservedFlags => "live-owner record reserved flags must be zero",
            Self::InvalidRecordLength => "invalid live-owner record length",
            Self::ZeroFence => "live-owner fence must be non-zero",
            Self::ZeroAuthorityAttemptId => "live-owner authority attempt ID must be non-zero",
            Self::PeerBindingMismatch => "live-owner key and record peer binding mismatch",
            Self::LengthOverflow => "live-owner encoded length overflow",
        };
        formatter.write_str(message)
    }
}

impl std::error::Error for ReachabilityLiveOwnerCodecError {}

/// Encodes one exact `DeviceId + TransportIdentity` namespace into the selected binary etcd key.
///
/// # Errors
///
/// Returns [`ReachabilityLiveOwnerCodecError::LengthOverflow`] if the source DeviceId length cannot
/// be represented canonically in the selected host/storage widths.
pub fn encode_live_owner_key(
    peer: &PeerConnectivityIdentity,
) -> Result<Vec<u8>, ReachabilityLiveOwnerCodecError> {
    let device_bytes = peer.device_id().as_str().as_bytes();
    let device_len =
        u64::try_from(device_bytes.len()).map_err(|_| ReachabilityLiveOwnerCodecError::LengthOverflow)?;
    let capacity = LIVE_OWNER_KEY_PREFIX
        .len()
        .checked_add(KEY_VERSION_BYTES + DEVICE_ID_LENGTH_BYTES)
        .and_then(|value| value.checked_add(device_bytes.len()))
        .and_then(|value| value.checked_add(TRANSPORT_IDENTITY_BYTES))
        .ok_or(ReachabilityLiveOwnerCodecError::LengthOverflow)?;

    let mut encoded = Vec::with_capacity(capacity);
    encoded.extend_from_slice(LIVE_OWNER_KEY_PREFIX);
    encoded.extend_from_slice(&LIVE_OWNER_KEY_MAJOR.to_be_bytes());
    encoded.extend_from_slice(&LIVE_OWNER_KEY_MINOR.to_be_bytes());
    encoded.extend_from_slice(&device_len.to_be_bytes());
    encoded.extend_from_slice(device_bytes);
    encoded.extend_from_slice(peer.transport_identity().as_bytes());
    Ok(encoded)
}

/// Decodes and canonically validates one selected binary live-owner etcd key.
///
/// # Errors
///
/// Returns a fail-closed [`ReachabilityLiveOwnerCodecError`] for malformed, non-canonical or
/// unsupported key bytes.
pub fn decode_live_owner_key(
    encoded: &[u8],
) -> Result<PeerConnectivityIdentity, ReachabilityLiveOwnerCodecError> {
    if !encoded.starts_with(LIVE_OWNER_KEY_PREFIX) {
        return Err(ReachabilityLiveOwnerCodecError::InvalidKeyPrefix);
    }

    let mut cursor = LIVE_OWNER_KEY_PREFIX.len();
    let major = u16::from_be_bytes(read_array::<2>(
        encoded,
        &mut cursor,
        ReachabilityLiveOwnerCodecError::InvalidKeyLength,
    )?);
    let minor = u16::from_be_bytes(read_array::<2>(
        encoded,
        &mut cursor,
        ReachabilityLiveOwnerCodecError::InvalidKeyLength,
    )?);
    if major != LIVE_OWNER_KEY_MAJOR || minor != LIVE_OWNER_KEY_MINOR {
        return Err(ReachabilityLiveOwnerCodecError::UnsupportedKeyVersion);
    }

    let device_len_u64 = u64::from_be_bytes(read_array::<8>(
        encoded,
        &mut cursor,
        ReachabilityLiveOwnerCodecError::InvalidKeyLength,
    )?);
    let device_len = usize::try_from(device_len_u64)
        .map_err(|_| ReachabilityLiveOwnerCodecError::InvalidKeyLength)?;
    let expected_len = cursor
        .checked_add(device_len)
        .and_then(|value| value.checked_add(TRANSPORT_IDENTITY_BYTES))
        .ok_or(ReachabilityLiveOwnerCodecError::InvalidKeyLength)?;
    if encoded.len() != expected_len {
        return Err(ReachabilityLiveOwnerCodecError::InvalidKeyLength);
    }

    let device_end = cursor + device_len;
    let device_bytes = &encoded[cursor..device_end];
    cursor = device_end;
    let device_text =
        str::from_utf8(device_bytes).map_err(|_| ReachabilityLiveOwnerCodecError::InvalidDeviceId)?;
    let device_id = DeviceId::new(device_text.to_owned())
        .map_err(|_| ReachabilityLiveOwnerCodecError::InvalidDeviceId)?;

    let transport_bytes = read_array::<TRANSPORT_IDENTITY_BYTES>(
        encoded,
        &mut cursor,
        ReachabilityLiveOwnerCodecError::InvalidKeyLength,
    )?;
    let transport_identity = TransportIdentity::new(transport_bytes)
        .map_err(|_| ReachabilityLiveOwnerCodecError::InvalidTransportIdentity)?;
    debug_assert_eq!(cursor, encoded.len());

    Ok(PeerConnectivityIdentity::new(device_id, transport_identity))
}

/// Encodes the selected full PRW fence as exactly 16 unsigned big-endian bytes.
#[must_use]
pub const fn encode_live_owner_fence(fence: NonZeroU128) -> [u8; LIVE_OWNER_FENCE_BYTES] {
    fence.get().to_be_bytes()
}

/// Decodes the selected 16-byte PRW fence representation.
///
/// # Errors
///
/// Returns [`ReachabilityLiveOwnerCodecError::ZeroFence`] for the prohibited zero value.
pub fn decode_live_owner_fence(
    encoded: [u8; LIVE_OWNER_FENCE_BYTES],
) -> Result<NonZeroU128, ReachabilityLiveOwnerCodecError> {
    NonZeroU128::new(u128::from_be_bytes(encoded)).ok_or(ReachabilityLiveOwnerCodecError::ZeroFence)
}

/// Encodes one canonical complete `PRWL` v1.0 live-owner authority record.
///
/// # Errors
///
/// Returns [`ReachabilityLiveOwnerCodecError::LengthOverflow`] if the DeviceId length cannot be
/// represented canonically in the selected record widths.
pub fn encode_live_owner_record(
    record: &ReachabilityLiveOwnerAuthorityRecord,
) -> Result<Vec<u8>, ReachabilityLiveOwnerCodecError> {
    let device_bytes = record.peer.device_id().as_str().as_bytes();
    let device_len =
        u64::try_from(device_bytes.len()).map_err(|_| ReachabilityLiveOwnerCodecError::LengthOverflow)?;
    let capacity = LIVE_OWNER_RECORD_FIXED_BYTES
        .checked_add(device_bytes.len())
        .ok_or(ReachabilityLiveOwnerCodecError::LengthOverflow)?;

    let mut encoded = Vec::with_capacity(capacity);
    encoded.extend_from_slice(&LIVE_OWNER_RECORD_MAGIC);
    encoded.extend_from_slice(&LIVE_OWNER_RECORD_MAJOR.to_be_bytes());
    encoded.extend_from_slice(&LIVE_OWNER_RECORD_MINOR.to_be_bytes());
    encoded.extend_from_slice(&record.lifecycle.encoded().to_be_bytes());
    encoded.extend_from_slice(&0_u16.to_be_bytes());
    encoded.extend_from_slice(&device_len.to_be_bytes());
    encoded.extend_from_slice(device_bytes);
    encoded.extend_from_slice(record.peer.transport_identity().as_bytes());
    encoded.extend_from_slice(&encode_live_owner_fence(record.fence));
    encoded.extend_from_slice(record.attempt_id.as_bytes());
    Ok(encoded)
}

/// Decodes and canonically validates one complete `PRWL` v1.0 authority record.
///
/// # Errors
///
/// Returns a fail-closed [`ReachabilityLiveOwnerCodecError`] for malformed, unsupported,
/// non-canonical or invalid identity/generation bytes.
pub fn decode_live_owner_record(
    encoded: &[u8],
) -> Result<ReachabilityLiveOwnerAuthorityRecord, ReachabilityLiveOwnerCodecError> {
    let mut cursor = 0;
    let magic = read_array::<4>(
        encoded,
        &mut cursor,
        ReachabilityLiveOwnerCodecError::InvalidRecordLength,
    )?;
    if magic != LIVE_OWNER_RECORD_MAGIC {
        return Err(ReachabilityLiveOwnerCodecError::InvalidRecordMagic);
    }

    let major = u16::from_be_bytes(read_array::<2>(
        encoded,
        &mut cursor,
        ReachabilityLiveOwnerCodecError::InvalidRecordLength,
    )?);
    let minor = u16::from_be_bytes(read_array::<2>(
        encoded,
        &mut cursor,
        ReachabilityLiveOwnerCodecError::InvalidRecordLength,
    )?);
    if major != LIVE_OWNER_RECORD_MAJOR || minor != LIVE_OWNER_RECORD_MINOR {
        return Err(ReachabilityLiveOwnerCodecError::UnsupportedRecordVersion);
    }

    let lifecycle = LiveOwnerLifecycle::try_from(u16::from_be_bytes(read_array::<2>(
        encoded,
        &mut cursor,
        ReachabilityLiveOwnerCodecError::InvalidRecordLength,
    )?))?;
    let reserved = u16::from_be_bytes(read_array::<2>(
        encoded,
        &mut cursor,
        ReachabilityLiveOwnerCodecError::InvalidRecordLength,
    )?);
    if reserved != 0 {
        return Err(ReachabilityLiveOwnerCodecError::NonZeroReservedFlags);
    }

    let device_len_u64 = u64::from_be_bytes(read_array::<8>(
        encoded,
        &mut cursor,
        ReachabilityLiveOwnerCodecError::InvalidRecordLength,
    )?);
    let device_len = usize::try_from(device_len_u64)
        .map_err(|_| ReachabilityLiveOwnerCodecError::InvalidRecordLength)?;
    let expected_len = LIVE_OWNER_RECORD_FIXED_BYTES
        .checked_add(device_len)
        .ok_or(ReachabilityLiveOwnerCodecError::InvalidRecordLength)?;
    if encoded.len() != expected_len {
        return Err(ReachabilityLiveOwnerCodecError::InvalidRecordLength);
    }

    let device_end = cursor + device_len;
    let device_bytes = &encoded[cursor..device_end];
    cursor = device_end;
    let device_text =
        str::from_utf8(device_bytes).map_err(|_| ReachabilityLiveOwnerCodecError::InvalidDeviceId)?;
    let device_id = DeviceId::new(device_text.to_owned())
        .map_err(|_| ReachabilityLiveOwnerCodecError::InvalidDeviceId)?;

    let transport_bytes = read_array::<TRANSPORT_IDENTITY_BYTES>(
        encoded,
        &mut cursor,
        ReachabilityLiveOwnerCodecError::InvalidRecordLength,
    )?;
    let transport_identity = TransportIdentity::new(transport_bytes)
        .map_err(|_| ReachabilityLiveOwnerCodecError::InvalidTransportIdentity)?;
    let fence = decode_live_owner_fence(read_array::<LIVE_OWNER_FENCE_BYTES>(
        encoded,
        &mut cursor,
        ReachabilityLiveOwnerCodecError::InvalidRecordLength,
    )?)?;
    let attempt_id = AuthorityAttemptId::new(read_array::<AUTHORITY_ATTEMPT_ID_BYTES>(
        encoded,
        &mut cursor,
        ReachabilityLiveOwnerCodecError::InvalidRecordLength,
    )?)?;
    debug_assert_eq!(cursor, encoded.len());

    Ok(ReachabilityLiveOwnerAuthorityRecord {
        peer: PeerConnectivityIdentity::new(device_id, transport_identity),
        lifecycle,
        fence,
        attempt_id,
    })
}

/// Decodes an exact key and record together and enforces the selected duplicate peer binding.
///
/// # Errors
///
/// Returns [`ReachabilityLiveOwnerCodecError::PeerBindingMismatch`] when both inputs are individually
/// canonical but encode different exact peers; other malformed input errors are propagated.
pub fn decode_bound_live_owner_record(
    key: &[u8],
    value: &[u8],
) -> Result<ReachabilityLiveOwnerAuthorityRecord, ReachabilityLiveOwnerCodecError> {
    let key_peer = decode_live_owner_key(key)?;
    let record = decode_live_owner_record(value)?;
    if record.peer != key_peer {
        return Err(ReachabilityLiveOwnerCodecError::PeerBindingMismatch);
    }
    Ok(record)
}

fn read_array<const N: usize>(
    encoded: &[u8],
    cursor: &mut usize,
    length_error: ReachabilityLiveOwnerCodecError,
) -> Result<[u8; N], ReachabilityLiveOwnerCodecError> {
    let end = cursor.checked_add(N).ok_or(length_error)?;
    let source = encoded.get(*cursor..end).ok_or(length_error)?;
    let mut result = [0_u8; N];
    result.copy_from_slice(source);
    *cursor = end;
    Ok(result)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn peer(device: &str, transport_marker: u8) -> PeerConnectivityIdentity {
        let device_id = DeviceId::new(device).expect("valid test DeviceId");
        let mut transport = [0_u8; TRANSPORT_IDENTITY_BYTES];
        transport[TRANSPORT_IDENTITY_BYTES - 1] = transport_marker;
        let transport_identity =
            TransportIdentity::new(transport).expect("non-zero test TransportIdentity");
        PeerConnectivityIdentity::new(device_id, transport_identity)
    }

    fn fence(value: u128) -> NonZeroU128 {
        NonZeroU128::new(value).expect("non-zero test fence")
    }

    fn attempt(marker: u8) -> AuthorityAttemptId {
        let mut bytes = [0_u8; AUTHORITY_ATTEMPT_ID_BYTES];
        bytes[AUTHORITY_ATTEMPT_ID_BYTES - 1] = marker;
        AuthorityAttemptId::new(bytes).expect("non-zero test attempt ID")
    }

    #[test]
    fn key_roundtrips_delimiter_like_unicode_and_nul_device_bytes() {
        let source = peer("device/α:β\0tail", 7);
        let encoded = encode_live_owner_key(&source).expect("encode key");
        let decoded = decode_live_owner_key(&encoded).expect("decode key");

        assert_eq!(decoded, source);
        assert!(encoded.starts_with(LIVE_OWNER_KEY_PREFIX));
    }

    #[test]
    fn distinct_exact_peers_encode_to_distinct_keys() {
        let one = encode_live_owner_key(&peer("device/a", 1)).expect("encode first key");
        let different_device =
            encode_live_owner_key(&peer("device:a", 1)).expect("encode second key");
        let different_transport =
            encode_live_owner_key(&peer("device/a", 2)).expect("encode third key");

        assert_ne!(one, different_device);
        assert_ne!(one, different_transport);
        assert_ne!(different_device, different_transport);
    }

    #[test]
    fn key_decoder_rejects_version_utf8_zero_transport_length_and_trailing_bytes() {
        let source = peer("valid", 9);
        let canonical = encode_live_owner_key(&source).expect("encode canonical key");
        let version_offset = LIVE_OWNER_KEY_PREFIX.len();
        let device_length_offset = version_offset + KEY_VERSION_BYTES;
        let device_offset = device_length_offset + DEVICE_ID_LENGTH_BYTES;

        let mut wrong_version = canonical.clone();
        wrong_version[version_offset..version_offset + 2].copy_from_slice(&2_u16.to_be_bytes());
        assert_eq!(
            decode_live_owner_key(&wrong_version),
            Err(ReachabilityLiveOwnerCodecError::UnsupportedKeyVersion)
        );

        let mut invalid_utf8 = canonical.clone();
        invalid_utf8[device_offset] = 0xff;
        assert_eq!(
            decode_live_owner_key(&invalid_utf8),
            Err(ReachabilityLiveOwnerCodecError::InvalidDeviceId)
        );

        let mut zero_transport = canonical.clone();
        let transport_start = zero_transport.len() - TRANSPORT_IDENTITY_BYTES;
        zero_transport[transport_start..].fill(0);
        assert_eq!(
            decode_live_owner_key(&zero_transport),
            Err(ReachabilityLiveOwnerCodecError::InvalidTransportIdentity)
        );

        let mut impossible_length = canonical.clone();
        impossible_length[device_length_offset..device_length_offset + DEVICE_ID_LENGTH_BYTES]
            .copy_from_slice(&u64::MAX.to_be_bytes());
        assert_eq!(
            decode_live_owner_key(&impossible_length),
            Err(ReachabilityLiveOwnerCodecError::InvalidKeyLength)
        );

        let mut trailing = canonical;
        trailing.push(0);
        assert_eq!(
            decode_live_owner_key(&trailing),
            Err(ReachabilityLiveOwnerCodecError::InvalidKeyLength)
        );
    }

    #[test]
    fn current_and_released_records_roundtrip_exactly() {
        let current = ReachabilityLiveOwnerAuthorityRecord::current(
            peer("record/α", 11),
            fence(0x0102_0304_0506_0708_1112_1314_1516_1718),
            attempt(12),
        );
        let released = current.released_successor();

        for source in [current, released] {
            let encoded = encode_live_owner_record(&source).expect("encode record");
            let decoded = decode_live_owner_record(&encoded).expect("decode record");
            assert_eq!(decoded, source);
            assert_eq!(encoded.len(), LIVE_OWNER_RECORD_FIXED_BYTES + source.peer().device_id().as_str().len());
        }
    }

    #[test]
    fn record_decoder_rejects_header_generation_identity_and_trailing_corruption() {
        let source = ReachabilityLiveOwnerAuthorityRecord::current(
            peer("valid", 15),
            fence(42),
            attempt(16),
        );
        let canonical = encode_live_owner_record(&source).expect("encode canonical record");
        let device_len = source.peer().device_id().as_str().len();
        let device_offset = LIVE_OWNER_RECORD_HEADER_BYTES + DEVICE_ID_LENGTH_BYTES;
        let transport_offset = device_offset + device_len;
        let fence_offset = transport_offset + TRANSPORT_IDENTITY_BYTES;
        let attempt_offset = fence_offset + LIVE_OWNER_FENCE_BYTES;

        let mut wrong_magic = canonical.clone();
        wrong_magic[0] = b'X';
        assert_eq!(
            decode_live_owner_record(&wrong_magic),
            Err(ReachabilityLiveOwnerCodecError::InvalidRecordMagic)
        );

        let mut wrong_version = canonical.clone();
        wrong_version[4..6].copy_from_slice(&2_u16.to_be_bytes());
        assert_eq!(
            decode_live_owner_record(&wrong_version),
            Err(ReachabilityLiveOwnerCodecError::UnsupportedRecordVersion)
        );

        let mut wrong_lifecycle = canonical.clone();
        wrong_lifecycle[8..10].copy_from_slice(&3_u16.to_be_bytes());
        assert_eq!(
            decode_live_owner_record(&wrong_lifecycle),
            Err(ReachabilityLiveOwnerCodecError::InvalidLifecycle)
        );

        let mut nonzero_flags = canonical.clone();
        nonzero_flags[10..12].copy_from_slice(&1_u16.to_be_bytes());
        assert_eq!(
            decode_live_owner_record(&nonzero_flags),
            Err(ReachabilityLiveOwnerCodecError::NonZeroReservedFlags)
        );

        let mut invalid_utf8 = canonical.clone();
        invalid_utf8[device_offset] = 0xff;
        assert_eq!(
            decode_live_owner_record(&invalid_utf8),
            Err(ReachabilityLiveOwnerCodecError::InvalidDeviceId)
        );

        let mut zero_transport = canonical.clone();
        zero_transport[transport_offset..transport_offset + TRANSPORT_IDENTITY_BYTES].fill(0);
        assert_eq!(
            decode_live_owner_record(&zero_transport),
            Err(ReachabilityLiveOwnerCodecError::InvalidTransportIdentity)
        );

        let mut zero_fence = canonical.clone();
        zero_fence[fence_offset..fence_offset + LIVE_OWNER_FENCE_BYTES].fill(0);
        assert_eq!(
            decode_live_owner_record(&zero_fence),
            Err(ReachabilityLiveOwnerCodecError::ZeroFence)
        );

        let mut zero_attempt = canonical.clone();
        zero_attempt[attempt_offset..attempt_offset + AUTHORITY_ATTEMPT_ID_BYTES].fill(0);
        assert_eq!(
            decode_live_owner_record(&zero_attempt),
            Err(ReachabilityLiveOwnerCodecError::ZeroAuthorityAttemptId)
        );

        let mut trailing = canonical;
        trailing.push(0);
        assert_eq!(
            decode_live_owner_record(&trailing),
            Err(ReachabilityLiveOwnerCodecError::InvalidRecordLength)
        );
    }

    #[test]
    fn exact_key_record_peer_binding_fails_closed_on_mismatch() {
        let key = encode_live_owner_key(&peer("peer-a", 21)).expect("encode key");
        let record = ReachabilityLiveOwnerAuthorityRecord::current(
            peer("peer-b", 21),
            fence(77),
            attempt(22),
        );
        let value = encode_live_owner_record(&record).expect("encode record");

        assert_eq!(
            decode_bound_live_owner_record(&key, &value),
            Err(ReachabilityLiveOwnerCodecError::PeerBindingMismatch)
        );
    }

    #[test]
    fn fence_encoding_is_exact_unsigned_big_endian_and_zero_is_rejected() {
        let source = fence(0x0102_0304_0506_0708_1112_1314_1516_1718);
        let encoded = encode_live_owner_fence(source);

        assert_eq!(encoded, source.get().to_be_bytes());
        assert_eq!(decode_live_owner_fence(encoded), Ok(source));
        assert_eq!(
            decode_live_owner_fence([0_u8; LIVE_OWNER_FENCE_BYTES]),
            Err(ReachabilityLiveOwnerCodecError::ZeroFence)
        );
    }

    #[test]
    fn released_successor_preserves_peer_fence_and_attempt_id() {
        let current = ReachabilityLiveOwnerAuthorityRecord::current(
            peer("release-peer", 31),
            fence(u128::MAX),
            attempt(32),
        );
        let released = current.released_successor();

        assert_eq!(released.lifecycle(), LiveOwnerLifecycle::Released);
        assert_eq!(released.peer(), current.peer());
        assert_eq!(released.fence(), current.fence());
        assert_eq!(released.attempt_id(), current.attempt_id());
    }
}
